### ISSUE TITLE
Error associated with this function

### ISSUE THREAD

**Issue by fssem1** [commfish/weiRends#1]
https://github.com/commfish/weiRends/blob/b40e3cdbd554b0f0def79d710edd7c7e21303b29/code/functions.r#L260

**Comment by fssem1** [comment]
![Error pic](https://user-images.githubusercontent.com/13024395/55041333-6effbb00-4fe1-11e9-8a81-fcbba4be8917.png)

**Comment by ben-williams** [comment]
for which population. just ran it on situk and it runs fine? May need to update some of your packages?

**Comment by fssem1** [comment]
The error only occurs withe egegik.

**Comment by ben-williams** [comment]
if you run it on the gomp model it will work fine. My guess is that since the prediction doesn't include the logistic it is creating an error - haven't checked.
