### ISSUE TITLE
f_run_risk function output

### ISSUE THREAD

**Issue by fssem1** [commfish/weiRends#10]
https://github.com/commfish/weiRends/blob/b9412468c3d559c3dab06af11e0c023d91b4ce10/code/situk_analysis.r#L95

f_run_caught is the percent of the run caught at a given risk level. 
Therefore, the plot f_risk_plot is the data from the function f_run_caught (but the % missed instead of % caught). This figure and the output data from f_run_caught line up. 

The function f_run_risk should also line up with the plot f_risk_plot. It seems to be way off. My R markdown file has both the table outputs and the figures. 

Figure 3 lines up nicely with the data in table 1.  When I try to line up data in table 3 with figure 3, it does not work. I'm not sure the problem. Unless I am misinterpreting these tables, maybe we should just delete table 3 (function f_run_risk) from the output unless the function can be fixed. It could be the binning deal also. If so, maybe we need to add a note to the table output.

**Comment by ben-williams** [comment]
I think you are reading the tables incorrectly.

First is the `f_run_caught` - this generates the percent of the run that is caught at a given risk level e.g., there is a 95% chance that 93% of the run will be captured using the five day 1% rule

Next is the  `f_run_risk` which is the percent of **risk** that a given % of the run is missed. This is quite a bit different from the `f_run_caught` e.g., 5% of the run will be missed 2.3% of the time using a five day 1% rule
