### ISSUE TITLE
example for Egegik

### ISSUE THREAD

**Issue by fssem1** [commfish/weiRends#13]
https://github.com/commfish/weiRends/blob/7796c69db6bd28bd38c3423e6cfac53dcf9e4c3d/output/report.Rmd#L129

May need to change to '5% risk that 4% (see 3.36% in table) of the run will be missed using a five day 1% rule for the Egegik River.

days   `99`    `95`  `90`  `80`    `70`  `60`  `50`
--
<chr> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1 five   6.65  3.36    2.42  1.93  1.28 0.869 0.682
2 four   6.65  3.94    2.92  2.48  1.67 1.12    0.910
3 one    7.14  5.19    4.79  3.30  2.77 2.22    1.76
4 three  6.65  4.45    3.31  2.67  1.82 1.46    1.09
5 two    6.77  4.96    4.09  3.11  2.35 1.77    1.28 |   |   |   |   |   |

**Comment by ben-williams** [comment]
addressed
