### ISSUE TITLE
Chilkoot example 0.05% rule

### ISSUE THREAD

**Issue by fssem1** [commfish/weiRends#14]
https://github.com/commfish/weiRends/blob/7796c69db6bd28bd38c3423e6cfac53dcf9e4c3d/output/report.Rmd#L206

I think this should be :
Figure 9: The percent of risk that a given % of the run is missed, e.g., 5% risk (or chance) that 7% of the run will be missed using a five day 0.05% rule for the Chilkoot River.

Also, since Table 8 rounds up, it may be more correct to use "roughly 8% of the run will be missed," instead of 7%. Likewise, for the other examples I referenced.

days     `99`  `95`  `90`    `80`  `70`  `60`    `50`
--
<chr> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1 five   9.10  7.12    5.74  3.41  3.03    2.55  2.05
2 four   9.43  7.52    6.10  3.57  3.28    2.79  2.15
3 one   10.2   8.83    7.31  4.37  3.91    3.08  2.58
4 three  9.67  7.93    6.45  3.77  3.40    2.86  2.30
5 two    9.85  8.37    6.86  4.03  3.71    2.89  2.40 |   |   |   |   |   |

**Comment by ben-williams** [comment]
addressed
