### ISSUE TITLE
Situk example

### ISSUE THREAD

**Issue by fssem1** [commfish/weiRends#17]
https://github.com/commfish/weiRends/blob/bdaa5905c524604028bf000c6e51c3d9bc4669cd/output/report.Rmd#L258

I think this should be "5% risk that 9% (or 10% depending on which you prefer) of the run will be missed using the five day 1% rule for the Situk River."

Once again, 10% would match Table 11, but 9% is more accurate.

  days   `99`  `95`  `90`  `80`  `70`  `60`  `50`
  <chr> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
1 five   10.2  9.08  8.97  7.74  6.84  6.41  5.88
2 four   10.4  9.56  9.11  8.58  7.12  6.57  5.88
3 one    10.6 10.4  10.2   9.11  7.66  6.84  6.41
4 three  10.5  9.98  9.54  8.95  7.66  6.57  5.91
5 two    10.6 10.3   9.83  9.11  7.66  6.57  6.40

**Comment by ben-williams** [comment]
addressed
