### ISSUE TITLE
Situk example 0.05% Rule

### ISSUE THREAD

**Issue by fssem1** [commfish/weiRends#18]
https://github.com/commfish/weiRends/blob/bdaa5905c524604028bf000c6e51c3d9bc4669cd/output/report.Rmd#L286

Change to: 
Figure 14: The percent of risk that a given % of the run is missed, e.g., 5% risk that 4% of the run is  missed using a five day 0.05% rule for the Situk River.

**Comment by ben-williams** [comment]
addressed
