### ISSUE TITLE
Change hard end date to 90% instead of 95% (see email below)

### ISSUE THREAD

**Issue by fssem1** [commfish/weiRends#23]
4/23/2019
In my notes from out meeting with Scott Raborn, I had written down that for a “hard” end date for counting operations, to use the date when 95% of the run was counted, with 95% confidence.  95% of the run was recommended.  However, I see in the email he sent out regarding UCI and Bristol Bay stocks, he recommend “a date be chosen to ensure a 95% chance of counting at least 90% of the escapement”.   That is apparently the plan that was set in motion from Scott’s work.  I don’t know how that would affect your analysis – or if it would be easy to change code and rerun for comparison.

I also noticed from Scott’s spreadsheet summary in his 2007 email that some of the end date ranges for the 3-day rule were close to the hard date (Egegik, Nushagak, Wood, Igushik).  For example, the hard ending date for Egegik was 16 July, with an ending range of 16 July to 22 July.  Sort of similar to what we were talking about with Chilkoot.  I’m wondering if the project could actually end on the hard end date if daily escapements up to that date were less than 1% of the cumulative escapement?  

Steve Heinl

**Comment by ben-williams** [comment]
@fssem1 
Updated the functions - specifically `f_run_through()` 
take a look and see if you think it looks ok. I've started adjusting the text, but haven't pushed that up yet. 
in hindsight i should have created a branch for all this c'est la vie

**Comment by fssem1** [comment]
It looks correct although now the run_95 variable is a bit confusing (since it now refers to 90% of the run).
