### ISSUE TITLE
remove_dates

### ISSUE THREAD

**Issue by Sages11** [commfish/weiRends#6]
There is over 30 years worth of data for Situk.
There are only remove_dates for 9 of those years. 
Of those 9 years some of them don't have removal dates based on the 1% rule for 5,4,3, and 2 days.

**Comment by fssem1** [comment]
I added a function called f_run_caught_n. It basically calculates the number of years of data represented in the 1% rule for 5,4,3, and 2 days.

**Comment by fssem1** [comment]
Although this function shows the number of years that the 1% rule is using, it is not clear why the other years are not involved in the 1% rule (i.e. does the rule need to be 0.5% for these years?)
