### ISSUE TITLE
Plot 

### ISSUE THREAD

**Issue by Sages11** [commfish/weiRends#9]
https://github.com/commfish/weiRends/blob/a3a2dd8706b9430435082a969ef389a73fe9e942/code/functions.r#L124

There are round points that don't match up with circles and vice versa.

Also his plot is good for general trends but is hard to read because of overlapping lines, and blending colors. Decadal plots might help. It would be nice to see the start dates for weir operations, although perhaps that isn't very possible for this plot. 

Additionally if stopping dates based on the 2-5 day 1% rules for either the simple logistic or the Gompertz logistic model were shown trends between low escapement and high escapement years could be evaluated.
Verticle lines for the median and CI's for each rule could be plotted. 

![image](https://user-images.githubusercontent.com/16549248/55186635-e3566d80-514b-11e9-8a37-d6b2ff690f23.png)

**Comment by fssem1** [comment]
Added decadel plots in the Rmarkdown file.
The two round points were errors in the original Situk data. So I fixed them in the clean up code (there were multiple

**Comment by ben-williams** [comment]
Note that this plot was only used for examination of the fits by the coder - not for presentation. As Sara mentioned the random points are in the original data - I have not justification for their removal so left them in.
